from colorama import * #coloring text using lib instead of ANSI escape codes
from google import genai #ai for word picking and /hint
import subprocess #copying to clipboard to share to friends
import os #clearing terminal
#to add- add support for mac

with open('keys.txt', 'r') as f:
    apikey = f.read()
print("loading...")
#init ai client for generating word and also hint
client = genai.Client(api_key=apikey)
#to make sure that ai doesnt show the same words over and over
words = []

def check(guess: str, answer: str, length: int):
    line = []
    for i in range(length): #iterate thru each character
        if guess[i] == answer[i]:
            line.append("green")
        elif guess[i] in answer: 
            line.append("yellow")
        elif guess[i] not in answer:
            line.append("grey")
    for i in range(len(line)):
        if line[i] == "green":
            print(Style.BRIGHT + Fore.WHITE + Back.GREEN + " " + guess[i] + " ", end="") #green
        elif line[i] == "yellow":
            print(Style.BRIGHT + Fore.WHITE + Back.YELLOW + " " + guess[i] + " ", end="") #yellow
        elif line[i] == "grey":
            print(Style.BRIGHT + Fore.WHITE + Back.LIGHTBLACK_EX + " " + guess[i] + " ", end="") #yello
    
    result = set(line)
    if result == "green" and len(result) == 1:
        return True
    
def pick_word(length):
    prompt = f'You are WordleBot. Your job is to create words to be fit in a wordle game. Here are your instructions: Generate a word (respond with only that one word): that is {length} letters long, is not one of these words: {words}, and respond in lowercase.'
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
    )
    return response.text
def hint(word: str, letters_guessed: list):
    prompt = f'You are HintBot. Respond with a short, one sentence hint that doesnt give it away, but just gives the player an idea of what the word is, for guessing a word in a wordle game. Your word is {word}'
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
    )
    return response.text

def share(guesses: list, answer: str, length: int):
    pass
    '''
    line = []
    for guess in guesses:
        for i in range(length): #iterate thru each character
            if guess[i] == answer[i]:
                line.append("green")
            elif guess[i] in answer: 
                line.append("yellow")
            elif guess[i] not in answer:
                line.append("grey")
    string = ""
    for i in line:
        if i == "green":
            string += "🟩"
        elif i == "yellow":
            string += "🟨"
        elif i == "grey":
            string += "⬛"
        if len(string) % length == 0:
            string += "\n"
        if len(string) == len(line):
            break

    string[0] == "Check out my wordle game!\n"
    string[-1] == "\nGenerated by: https://github.com/devan518/cli_wordle"
    if os.name == 'nt':
        subprocess.run("clip", input=string, check=True, encoding="utf-8")
    elif os.name == 'darwin': #macos according to chatgpt
        subprocess.run("pbcopy", input=string, check=True, encoding="utf-8")
    #add linux support here:
    return string
    '''

def main():
    if os.name == 'nt':
        os.system('cls') # Command for Windows
    else:
        os.system('clear') # Command for Linux/macOS
    banner = '''
 ██████╗ ██╗     ██╗
██╔════╝ ██║     ██║
██║      ██║     ██║
██║      ██║     ██║
╚██████╗ ███████╗██║
 ╚═════╝ ╚══════╝╚═╝

██╗    ██╗ ██████╗ ██████╗ ██████╗ ██╗     ███████╗
██║    ██║██╔═══██╗██╔══██╗██╔══██╗██║     ██╔════╝
██║ █╗ ██║██║   ██║██████╔╝██║  ██║██║     █████╗  
██║███╗██║██║   ██║██╔══██╗██║  ██║██║     ██╔══╝  
╚███╔███╔╝╚██████╔╝██║  ██║██████╔╝███████╗███████╗
 ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═════╝ ╚══════╝╚══════╝

Hello! This is my version of wordle, written as a cli!
features:
-generates word using ai instead of pre picked words so that is doesnt run out!
-use "/hint" as a command to get a hint!
-custom wordle length!

Note: This program requires internet for picking the word and /hint.

Keep in mind that slow internet may cause the program to act slow 
(its just the word picking and hint generation may take long)
----------------------
'''
    print(banner)
    while True:
        config_one = input("how much letters should your wordle be? (minimum is 3)")
        try:
            length = int(config_one)
        except ValueError:
            print("Error: Enter Valid Number!")
            continue
        if length < 3:
            print("Error: Enter Valid Number!")
            continue
        break
    
    init(autoreset=True) #colorama start coloring!
    word = pick_word(length)
    #game
    guesses = []
    print("Start guessing!")
    for count in range(6): #attempts left
        guess = input()
        guesses.append(guess) 
        if guess == "/hint":
            print(hint(word))
            continue
            #add feature to only allow on hint

        if len(guess) != len(word):
            if guess != "/hint":
                print("ERROR! THE INPUTTED GUESS IS NOT THE SAME LENGTH AS ANSWER")
        
        if check(guess, word, length) == True:
            print("\n You Won!")
            print(f"Share to your friends!\n {share(guesses, word, length)} \n It has been copied to your clipboard!")
            choice = input("Would you like to try again? (yes/no)")
            if choice == "yes":
                main()
            else:
                return
        else:
            pass
    print("\n You Lost!😔")
    print(f"The word was: {word}")
    choice = input("Would you like to try again? (yes/no)")
    if choice == "yes":
        main()
    else:
        return
    
if __name__ == "__main__":
    main()